# Generated by Django 4.0.6 on 2022-08-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repositorio', '0002_categoria_repositorio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='Descricao',
            field=models.CharField(max_length=3000),
        ),
    ]
